FROM python:3.13-slim

WORKDIR /app

# Установка системных утилит (нужно для сборки некоторых тяжелых библиотек)
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "admin_bot.py"]